### ISSUE TITLE
Quick start question

### ISSUE THREAD

**Issue by JieDing** [hitsz-ids/auto-regex#23]
How should I start to use this project? Is there any guides?

**Comment by hitsz-ids2021** [comment]
> How should I start to use this project? Is there any guides?

![image](https://user-images.githubusercontent.com/55747589/228185471-5b9fa5ec-3ffd-4598-b79e-966e48a1c170.png)
you can do it like this

**Comment by hitsz-ids2021** [comment]
follow last comment

**Comment by JieDing** [comment]
Ok, I will follow it to try.
